load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "executionattributes",
    srcs = [
        "cache.go",
        "cluster_settings.go",
        "doc.go",
        "gateway.go",
        "id.go",
        "metrics.go",
        "writer.go",
    ],
    importpath = "github.com/cockroachdb/cockroach/pkg/obs/executionattributes",
    visibility = ["//visibility:public"],
    deps = [
        "//pkg/settings",
        "//pkg/util/log",
        "//pkg/util/metric",
        "@com_github_cespare_xxhash_v2//:xxhash",
    ],
)

go_test(
    name = "executionattributes_test",
    srcs = [
        "cache_test.go",
        "gateway_test.go",
        "id_test.go",
        "writer_test.go",
    ],
    embed = [":executionattributes"],
)
